# Note: This only runs the Django app, not the rook services
FROM ubuntu:16.04
MAINTAINER Raman Prasad (raman_prasad@harvard.edu)

LABEL organization="Two Ravens" \
      2ra.vn.version="0.0.1-beta" \
      2ra.vn.release-date="2017-09-20" \
      description="Image for the Two Ravens python service which serves the UI."

# -------------------------------------
# Install some tools as well as python3
#  (future: start with a python image)
# -------------------------------------
RUN apt-get update && \
    apt-get install -y \
    iputils-ping \
    telnet \
    python3-pip \
    sqlite3 \
    vim && \
    ln -sf /usr/bin/python3 /usr/bin/python

# -------------------------------------
# Set some environment variables
#   (This can be overridden in docker compose)
# -------------------------------------

# Django settings
ENV DJANGO_SETTINGS_MODULE=tworavensproject.settings.dev_container2

# Set the R_DEV_SERVER_BASE to the rook-service docker container
ENV R_DEV_SERVER_BASE=http://rook-service:8000/custom/

# TA2_TEST_SERVER_URL should be overridden in docker-compose
ENV TA2_TEST_SERVER_URL=localhost:45042

# -------------------------------------
# Copy the repo over
#   - future: ignore the rook directory, be more selective
# -------------------------------------
RUN mkdir -p /var/webapps/TwoRavens && \
    mkdir -p /ravens_volume

# -------------------------------------
# Create a volume for outside info
# -------------------------------------
VOLUME /ravens_volume


# Copy over the repository
COPY . /var/webapps/TwoRavens


# -------------------------------------
# Set the working directory
# -------------------------------------
WORKDIR /var/webapps/TwoRavens

# -------------------------------------
# Pip install y'all and setup scripts
#  for db, etc
# -------------------------------------
RUN pip3 install --no-cache-dir -r requirements/prod.txt && \
    fab init_db && \
    fab create_django_superuser && \
    fab load_docker_ui_config

# -------------------------------------
# Expose ports for the web and gRPC communication
# -------------------------------------
EXPOSE 45042

WORKDIR /var/webapps/TwoRavens/tworaven_apps/ta2_interfaces

# -------------------------------------
# Run test server
# -------------------------------------
CMD python test_server.py


# -----------------------------------------
# -- Dev notes --
#
# -----------------
# build local:
# -----------------
# >docker build -t ta2-test:v2 -f Dockerfile-TA2-test .
#
# -----------------
# run app
# -----------------
# >docker run -p 45042:45042 ta2-test:v2
#
# -----------------
# > log into running app
# -----------------
# docker exec -it [container name] /bin/bash
#
# -----------------------------------------
