FROM tworavens/eventdata-r-service-base:latest
MAINTAINER Raman Prasad (raman_prasad@harvard.edu)

LABEL organization="Two Ravens" \
      2ra.vn.version="0.0.6-beta" \
      2ra.vn.release-date="2018-01-11" \
      description="R service for event data"

# -------------------------------------
# Copy the repo over
#   - future: ignore the tworavens django dirs
#     and assets, be more selective
# -------------------------------------
RUN mkdir -p /var/webapps/TwoRavens && \
    mkdir -p /var/webapps/TwoRavens/assets && \
    mkdir -p /ravens_volume

# Copy over the repository
COPY ./rook /var/webapps/TwoRavens/rook
COPY ./LICENSE /var/webapps/TwoRavens
COPY ./README.md /var/webapps/TwoRavens


# -------------------------------------
# Set production environment variable
# -------------------------------------
ENV FLASK_USE_PRODUCTION_MODE=yes \
    EVENTDATA_PRODUCTION_MODE=yes \
    EVENTDATA_PRODUCTION_SERVER_ADDRESS=http://149.165.156.33:5002/api/data? \
    EVENTDATA_SERVER_API_KEY="api_key=CD75737EF4CAC292EE17B85AAE4B6" \
    EVENTDATA_ROOK_URL_BASE=http://127.0.0.1:8000

# -------------------------------------
# Create a volume for outside info
# -------------------------------------
VOLUME /ravens_volume

# -------------------------------------
# Expose port for the web (rook)
# -------------------------------------
EXPOSE 8000

WORKDIR /var/webapps/TwoRavens/rook

# -------------------------------------
# Run django with "rook_nonstop.R"
# -------------------------------------
CMD Rscript rook_nonstop.R

# -----------------------------------------
# -- Dev notes --
#
# build local:
# >docker build -t rook2 -f ./Dockerfile-eventdata-r-service .
#
# shell access:
# >docker run -ti  -p 8000:8000 rook2 /usr/bin/bash
#
# run app
# >docker run -p 8000:8000 rook1
# go to: http://0.0.0.0:8000/subsetapp
# -----------------------------------------
