# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rook_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcallcapture',
            name='app_name',
            field=models.CharField(max_length=255),
        ),
    ]
