# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rook_services', '0002_auto_20170810_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcallcapture',
            options={'ordering': ('-created',), 'verbose_name': 'Rook Call Request', 'verbose_name_plural': 'Rook Call Requests'},
        ),
        migrations.AddField(
            model_name='testcallcapture',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Used for grouping calls together', max_length=255),
        ),
    ]
