apiVersion: v1
kind: Pod
metadata:
  name: raven-pod1
spec:
  volumes:
    # this can point to a volume with test data, etc
    - name: "raven-data1"
      hostPath:
        path: "/Users/ramanprasad/Documents/github-rp/TwoRavens/ravens_volume"
    - name: "isi-volume"
      emptyDir: {}
  containers:
    # -------------------------
    # NGINX CONTAINER SPECS
    # -------------------------
    - image: nginx:v2
      name: nginx
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      # current tworavens has a mount at /ravens_volume
      #volumeMounts:
      #  - mountPath: "/ravens_volume"
      #    name: "raven-data1"
    # -------------------------
    # TWO RAVENS CONTAINER SPECS
    # -------------------------
    - image: tworavens:v2
      name: tworavens
      # current tworavens has a mount at /ravens_volume
      volumeMounts:
        - mountPath: "/ravens_volume"
          name: "raven-data1"
        - mountPath: /tmp/dsbox-ta2/
          name: "isi-volume"
      # liveness is for restart
      livenessProbe:
        httpGet:
          path: /monitoring/alive
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      # readiness: ready for traffic
      readinessProbe:
        httpGet:
          path: /monitoring/alive
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
      # web and gRPC ports
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50051
          name: grpc
          protocol: TCP
      # environment variables passed to container
      env:
      - name: EVAL_ID
        value: ravens2
      - name: TA2_STATIC_TEST_MODE
        value: "False"
      - name: TA2_TEST_SERVER_URL
        value: "raven-pod1:50051"
      - name: CONFIG_JSON_PATH
        value: "/ravens_volume/config_o_196seed.json"
      - name: R_DEV_SERVER_BASE
        value: "http://localhost:8000/custom/"
    # -------------------------
    # ROOK CONTAINER SPECS
    # -------------------------
    - image: rook:v2
      name: rook
      # current rook has a mount at /ravens_volume
      volumeMounts:
        - mountPath: "/ravens_volume"
          name: "raven-data1"
        - mountPath: /tmp/dsbox-ta2/
          name: "isi-volume"
      # web port
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
      # liveness is for restart
      livenessProbe:
        httpGet:
          path: /custom/healthcheckapp
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      # readiness: ready for traffic
      readinessProbe:
        httpGet:
          path: /custom/healthcheckapp
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 10
    # -------------------------
    # TA2 TEST CONTAINER SPECS
    # -------------------------
    #- image: ta2-test:v2
    - image: ta2-isi:v2
      name: ta2-test
      # web port
      ports:
        - containerPort: 50051
          protocol: TCP
      volumeMounts:
        - mountPath: "/ravens_volume"
          name: "raven-data1"
        - mountPath: /tmp/dsbox-ta2/
          name: "isi-volume"
