# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_captures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecallentry',
            name='service_type',
            field=models.CharField(choices=[('ROOK SERVICE', 'ROOK SERVICE'), ('D3M SERVICE', 'D3M SERVICE'), ('service not specified', 'service not specified')], max_length=100),
        ),
    ]
