# 1st pass to build images
#
image: docker:latest
services:
  - docker:dind

build:
  script:
    #
    # Docker login
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.datadrivendiscovery.org
    #
    # Build r-service: fairly big image
    - docker build -t registry.datadrivendiscovery.org/tworavens/tworavens/rook-service:latest -f ./Dockerfile-rook .
    - docker push registry.datadrivendiscovery.org/tworavens/tworavens/rook-service:latest
    #
    # Build nginx image
    - docker build -t registry.datadrivendiscovery.org/tworavens/tworavens/nginx:latest -f setup/nginx/Dockerfile ./setup/nginx/
    - docker push registry.datadrivendiscovery.org/tworavens/tworavens/nginx:latest
    #
    # Build tworavens UI + python app 
    - docker build -t registry.datadrivendiscovery.org/tworavens/tworavens:latest .
    - docker push registry.datadrivendiscovery.org/tworavens/tworavens:latest
