# 1st pass to build images
#
image: docker:latest
services:
  - docker:dind

xbuild:
  script:
    #
    # Docker login
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.datadrivendiscovery.org
    #
    # Build nginx image
    - docker build -t registry.datadrivendiscovery.org/tworavens/tworavens/nginx -f setup/nginx/Dockerfile ./setup/nginx/
    - docker push registry.datadrivendiscovery.org/tworavens/tworavens/nginx
    #
    # Build tworavens UI + python app 
    - docker build -t registry.datadrivendiscovery.org/tworavens/tworavens/tworavens .
    - docker push registry.datadrivendiscovery.org/tworavens/tworavens/tworavens