# Note: This is only for D3M local testing
#
# Assumes local image built with:
#   `docker build -t ravens-main:stable .`
#
# Build: `docker build -t ta2-test:stable -f Dockerfile-TA2-test .`
# RUN: `docker run --name=ta2_server --rm -ti -p 45042:45042 ta2-test:stable`
#
FROM ravens-main:stable
MAINTAINER Raman Prasad (raman_prasad@harvard.edu)

# -------------------------------------
# Expose port for grpc communication
# -------------------------------------
EXPOSE 45042

# -------------------------------------
# Run the test server
# -------------------------------------
CMD echo 'Starting TA2 test server.' && \
    fab run_ta2_test_server
