# Generated by Django 2.0.3 on 2018-06-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveQueryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(default=None)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('message', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDataSavedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=None)),
                ('username', models.CharField(max_length=255)),
                ('result_count', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('saved_to_dataverse', models.BooleanField(default=False)),
                ('dataverse_url', models.URLField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='archivequeryjob',
            name='saved_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventdata_queries.EventDataSavedQuery'),
        ),
    ]
