# Generated by Django 2.0.5 on 2018-07-16 17:16

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveQueryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile_id', models.IntegerField(default=-1)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('message', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('dataverse_response', jsonfield.fields.JSONField(blank=True)),
                ('archive_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EventDataSavedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('username', models.CharField(max_length=255)),
                ('query', jsonfield.fields.JSONField(default=None)),
                ('result_count', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.TextField(blank=True)),
                ('dataset_type', models.CharField(choices=[('subset', 'subset'), ('aggregate', 'aggregate')], default='subset', max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='archivequeryjob',
            name='saved_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventdata_queries.EventDataSavedQuery'),
        ),
    ]
