# Generated by Django 2.0.5 on 2018-08-24 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveQueryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('datafile_id', models.IntegerField(default=-1, unique=True, verbose_name='Datverse file id')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('message', models.TextField(default=None)),
                ('dataverse_response', jsonfield.fields.JSONField(blank=True)),
                ('archive_url', models.URLField(blank=True)),
                ('hash_id', models.CharField(blank=True, help_text='(auto-generated)', max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EventDataSavedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query', jsonfield.fields.JSONField()),
                ('result_count', models.IntegerField(default=-1)),
                ('collection_type', models.CharField(choices=[('subset', 'subset'), ('aggregate', 'aggregate')], default='subset', max_length=255)),
                ('collection_name', models.CharField(default='mongo dataset', max_length=255)),
                ('save_to_dataverse', models.BooleanField(default=False)),
                ('hash_id', models.CharField(blank=True, help_text='(auto-generated)', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event data saved queries',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('emailed', models.BooleanField(db_index=True, default=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('archived_query', jsonfield.fields.JSONField()),
                ('hash_id', models.CharField(blank=True, help_text='(auto-generated)', max_length=255)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='archivequeryjob',
            name='saved_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventdata_queries.EventDataSavedQuery'),
        ),
    ]
