# Generated by Django 2.0.5 on 2018-08-23 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventdata_queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdatasavedquery',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Event data saved queries'},
        ),
        migrations.AlterUniqueTogether(
            name='eventdatasavedquery',
            unique_together={('user', 'collection_type', 'collection_name', 'query')},
        ),
    ]
