# Generated by Django 2.0.5 on 2018-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdatasavedquery',
            old_name='dataset_type',
            new_name='collection_type',
        ),
        migrations.RemoveField(
            model_name='eventdatasavedquery',
            name='dataset',
        ),
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='collection_name',
            field=models.CharField(default='mongo dataset', max_length=255),
        ),
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='save_to_dataverse',
            field=models.BooleanField(default=False),
        ),
    ]
