# Generated by Django 2.0.3 on 2018-06-20 16:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='query',
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
