# Generated by Django 2.0.5 on 2018-08-20 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventdata_queries', '0002_auto_20180819_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('archived_query', jsonfield.fields.JSONField(default=None)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='archivequeryjob',
            name='datafile_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
