# Generated by Django 2.0.5 on 2018-06-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0002_eventdatasavedquery_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivequeryjob',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='eventdatasavedquery',
            options={'ordering': ('-created',)},
        ),
    ]
