# Generated by Django 2.1.10 on 2019-12-02 18:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0002_auto_20181114_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('loading', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
