# Generated by Django 2.0.5 on 2018-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0003_auto_20180622_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdatasavedquery',
            name='dataverse_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventdatasavedquery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
