# Generated by Django 2.1.10 on 2019-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0003_mongodataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongodataset',
            name='id',
        ),
        migrations.AlterField(
            model_name='mongodataset',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
