# Generated by Django 2.0.5 on 2018-07-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0004_auto_20180623_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivequeryjob',
            old_name='what',
            new_name='description',
        ),
    ]
