# Generated by Django 2.0.5 on 2018-07-02 16:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0004_auto_20180623_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivequeryjob',
            name='what',
        ),
        migrations.AddField(
            model_name='archivequeryjob',
            name='archive_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='archivequeryjob',
            name='dataverse_response',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
