# Generated by Django 2.0.5 on 2018-07-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0006_archivequeryjob_datafile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='dataset',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='dataset_type',
            field=models.CharField(choices=[('subset', 'subset'), ('aggregate', 'aggregate')], default='subset', max_length=255),
        ),
    ]
