# Generated by Django 2.0.5 on 2018-07-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0007_auto_20180703_1456'),
        ('eventdata_queries', '0006_auto_20180702_1155'),
    ]

    operations = [
    ]
