# Generated by Django 2.0.5 on 2018-07-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0007_auto_20180703_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdatasavedquery',
            name='dataverse_url',
        ),
        migrations.RemoveField(
            model_name='eventdatasavedquery',
            name='saved_to_dataverse',
        ),
    ]
