# Generated by Django 2.0.5 on 2018-07-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0008_merge_20180706_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdatasavedquery',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='archivequeryjob',
            name='what',
        ),
    ]
