# Generated by Django 2.0.5 on 2018-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0008_auto_20180709_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivequeryjob',
            name='datafile_id',
            field=models.IntegerField(default=-1),
        ),
    ]
