# Generated by Django 2.0.5 on 2018-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0009_auto_20180710_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='save_to_dataverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdatasavedquery',
            name='user_dataset_name',
            field=models.CharField(default='mongo dataset', max_length=255),
        ),
    ]
