# Generated by Django 2.0.5 on 2018-07-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0010_auto_20180724_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdatasavedquery',
            old_name='user_dataset_name',
            new_name='collection_name',
        ),
        migrations.RenameField(
            model_name='eventdatasavedquery',
            old_name='dataset_type',
            new_name='collection_type',
        ),
        migrations.RemoveField(
            model_name='eventdatasavedquery',
            name='dataset',
        ),
    ]
