# Generated by Django 2.0.5 on 2018-08-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata_queries', '0012_usernotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivequeryjob',
            name='datafile_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
