# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedworkspace',
            name='data_source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.DataSourceType'),
        ),
    ]
