# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedworkspace',
            name='session_key',
            field=models.CharField(default='sess-key', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
