# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_savedworkspace_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedworkspace',
            name='session_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='savedworkspace',
            unique_together=set([('session_key', 'data_source_type')]),
        ),
    ]
