# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20171204_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datasourcetype',
            name='source_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
