# Generated by Django 2.0.5 on 2018-05-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20171220_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedworkspace',
            name='data_source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workspaces.DataSourceType'),
        ),
    ]
