# Generated by Django 2.1.3 on 2019-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_auto_20180523_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedworkspace',
            name='app_domain',
            field=models.CharField(choices=[('D3M_DOMAIN', 'D3M_DOMAIN'), ('DATAMART_ONLY_DOMAIN', 'DATAMART_ONLY_DOMAIN'), ('DATAVERSE_DOMAIN', 'DATAVERSE_DOMAIN'), ('EVENTDATA_DOMAIN', 'EVENTDATA_DOMAIN')], max_length=100),
        ),
    ]
