# Generated by Django 2.1.3 on 2019-01-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20190125_1213'),
        ('workspaces', '0006_auto_20190125_0024'),
    ]

    operations = [
    ]
