# Generated by Django 2.1.3 on 2019-01-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_merge_20190125_1217'),
        ('workspaces', '0006_auto_20190122_1624'),
    ]

    operations = [
    ]
