# Generated by Django 2.1.7 on 2019-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_merge_20190126_1723'),
        ('workspaces', '0008_merge_20190126_1658'),
    ]

    operations = [
    ]
