---
swagger: "2.0"
info:
  description: "This is a developers reference for TwoRavens work.\
    \ NOTE: Not for REST-like usage.  Most endpoints only are used by the UI\
    \ and require the user to be logged in."
  version: "1.0.0"
  title: "TwoRavens API doc"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "raman_prasad@harvard.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "{{ SWAGGER_HOST }}"
#basePath: "/api/v1"
tags:
- name: "workspaces"
  description: "Retrieve SavedWorkspace information"
- name: "ta2"
  description: "For D3M, API calls used by the UI to initiate requests to a TA2 system"
schemes:
- "http"
paths:
{% include "swagger/v1_paths_ta2.yaml" %}
{% include "swagger/v1_paths_workspace.yaml" %}
# ------------------------------
# Define reusable parameters:
# ------------------------------
definitions:
{% include "swagger/v1_defn_basic.yaml" %}
{% include "swagger/v1_defn_workspaces.yaml" %}
{% include "swagger/v1_defn_ta2.yaml" %}
