# Generated by Django 2.1.11 on 2019-12-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
