# Generated by Django 2.1.7 on 2019-06-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('session_key', models.CharField(blank=True, help_text='optional', max_length=255)),
                ('is_optional', models.BooleanField(default=False)),
                ('feature_id', models.CharField(blank=True, help_text='Auto-filled on save. A unique identifier of the system component', max_length=255)),
                ('type', models.CharField(choices=[('TA23API', 'TA23API'), ('DATAMART', 'DATAMART'), ('SYSTEM', 'SYSTEM')], max_length=100)),
                ('path', models.CharField(blank=True, help_text='May be used for recording Datamart paths or similar', max_length=255)),
                ('activity_l1', models.CharField(choices=[('SYSTEM_ACTIVITY', 'SYSTEM_ACTIVITY'), ('DATA_PREPARATION', 'DATA_PREPARATION'), ('PROBLEM_DEFINITION', 'PROBLEM_DEFINITION'), ('MODEL_SELECTION', 'MODEL_SELECTION')], help_text='"activity_l1" in spec', max_length=255)),
                ('activity_l2', models.CharField(default='(blank)', help_text='"activity_l2" in spec', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Behavioral log entries',
                'ordering': ('-created',),
            },
        ),
    ]
