# Generated by Django 2.1.7 on 2019-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorallogentry',
            name='other',
            field=models.CharField(blank=True, help_text='Optional field', max_length=255),
        ),
    ]
