# Generated by Django 2.1.7 on 2019-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorallogentry',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
