kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: raven-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: raven-app
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: nginx:v1
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
