# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='Two Ravens Configuration', help_text='Human readable name', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('production', models.BooleanField(help_text='.js variable "production". True -> data, metadata from live server resources instead of local versions', verbose_name='Production')),
                ('d3m_mode', models.BooleanField(help_text='.js variable "d3m". Are D3M services active?', verbose_name='D3M mode')),
                ('privacy_mode', models.BooleanField(help_text='.js variable "privacy". Is the PSI tool available?', verbose_name='Privacy (PSI) mode')),
                ('rook_app_url', models.URLField(help_text='URL to the rook server. examples: https://beta.dataverse.org/custom, http://0.0.0.0:8000/rook-custom', verbose_name='rappURL')),
                ('description', models.TextField(blank=True, help_text='optional')),
            ],
            options={
                'verbose_name': 'Two Ravens Configuration',
                'verbose_name_plural': 'Two Ravens Configurations',
                'db_table': 'tworavens_config',
                'ordering': ('is_active',),
            },
        ),
    ]
