# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfiguration',
            options={'ordering': ('-is_active',), 'verbose_name': 'Two Ravens Configuration', 'verbose_name_plural': 'Two Ravens Configurations'},
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Make this the active configuration. Once saved, any other configurations will be deactivated--but may be reused'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='name',
            field=models.CharField(help_text='e.g. "Dev Configuration"', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='rook_app_url',
            field=models.URLField(help_text='URL to the rook server. examples: https://beta.dataverse.org/custom/, http://127.0.0.1:8080/rook-custom/', verbose_name='rappURL (rook apps)'),
        ),
    ]
