# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_auto_20170901_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='dataverse_url',
            field=models.URLField(default='https://beta.dataverse.org', help_text='URL to Dataverseexamples: https://beta.dataverse.org,https://dataverse.harvard.edu', verbose_name='dataverse url'),
            preserve_default=False,
        ),
    ]
