# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_auto_20171120_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='app_domain',
            field=models.CharField(choices=[('D3M_DOMAIN', 'D3M_DOMAIN'), ('DATAVERSE_DOMAIN', 'DATAVERSE_DOMAIN'), ('EVENTDATA_DOMAIN', 'EVENTDATA_DOMAIN')], default='D3M_DOMAIN', max_length=70, verbose_name='App domain'),
            preserve_default=False,
        ),
    ]
