# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_appconfiguration_dataverse_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='d3m_url',
            field=models.URLField(default='http://127.0.0.1:8080/d3m-service', help_text='URL used to make calls that are converted to gRPC messages and sent to D3M applications', verbose_name='D3M url'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='rook_app_url',
            field=models.URLField(default='http://127.0.0.1:8080/rook-custom/', help_text='URL to the rook server. examples: https://beta.dataverse.org/custom/, http://127.0.0.1:8080/rook-custom/', verbose_name='rappURL (rook apps)'),
        ),
    ]
