# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_appconfiguration_app_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='d3m_mode',
        ),
    ]
