# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_auto_20170911_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='d3m_url',
            field=models.URLField(default='http://127.0.0.1:8080/d3m-service/', help_text='URL used to make calls that are converted to gRPC messages and sent to D3M applications', verbose_name='D3M url'),
        ),
    ]
