# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_auto_20170918_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='D3MConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Test data', max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='There can be either one default or no defaults')),
                ('dataset_schema', models.TextField(help_text='Input: Path to the dataset schema')),
                ('problem_schema', models.TextField(help_text='Input: Path to the problem schema')),
                ('training_data_root', models.TextField(help_text='Input: Path to the root directory of the dataset described by dataset_schema')),
                ('executables_root', models.TextField(blank=True, help_text='Output: Directory in which to write the Test Executables.')),
                ('slug', models.SlugField(blank=True, help_text='auto-filled on save')),
            ],
            options={
                'verbose_name': 'D3M Configuration',
                'verbose_name_plural': 'D3M Configurations',
                'ordering': ('name', '-modified'),
            },
        ),
        migrations.AlterModelOptions(
            name='appconfiguration',
            options={'ordering': ('-is_active',), 'verbose_name': 'Two Ravens UI Configuration', 'verbose_name_plural': 'Two Ravens UI Configurations'},
        ),
    ]
