# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20170918_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3mconfiguration',
            name='pipeline_list',
            field=models.TextField(blank=True, help_text='Output: Path at which performers should write the pipeline list, output described in Section 4.1.3'),
        ),
        migrations.AddField(
            model_name='d3mconfiguration',
            name='temp_storage_root',
            field=models.TextField(blank=True, help_text='Temporary storage root for performers to use.'),
        ),
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='name',
            field=models.CharField(help_text='for internal use', max_length=255, unique=True),
        ),
    ]
