# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20170918_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d3mconfiguration',
            old_name='pipeline_list',
            new_name='pipeline_logs_root',
        ),
    ]
