# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20171218_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='cpus',
            field=models.CharField(blank=True, help_text='Number of cpus available for search.', max_length=255),
        ),
    ]
