# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_auto_20170918_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='d3m_url',
            field=models.CharField(default='/d3m-service/', help_text='URL used to make calls that are converted to gRPC messages and sent to D3M applications', max_length=255, verbose_name='D3M url'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='rook_app_url',
            field=models.CharField(default='/rook-custom/', help_text='URL to the rook server. examples: https://beta.dataverse.org/custom/, http://127.0.0.1:8080/rook-custom/', max_length=255, verbose_name='rappURL (rook apps)'),
        ),
    ]
