# Generated by Django 2.0.5 on 2018-07-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_auto_20180709_1222'),
        ('configurations', '0010_auto_20180702_1220'),
    ]

    operations = [
    ]
