# Generated by Django 2.1.3 on 2019-01-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_auto_20190125_0024'),
        ('configurations', '0012_auto_20190125_1213'),
    ]

    operations = [
    ]
