# Generated by Django 2.1.3 on 2019-01-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0013_merge_20190125_1217'),
        ('configurations', '0012_auto_20190122_1624'),
    ]

    operations = [
    ]
