# Generated by Django 2.1.5 on 2019-01-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0015_auto_20190127_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='timeout',
            field=models.BigIntegerField(default=-1, help_text='Allotted time for search, in seconds. No timeout if negative.'),
        ),
    ]
