# Generated by Django 2.1.5 on 2019-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0016_auto_20190127_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3mconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='For internal use', max_length=255),
        ),
    ]
