# Generated by Django 2.1.5 on 2019-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0018_d3mconfiguration_env_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3mconfiguration',
            name='is_user_config',
            field=models.BooleanField(default=False, help_text='If true, must be used through a UserWorkspace'),
        ),
        migrations.AddField(
            model_name='d3mconfiguration',
            name='orig_dataset_id',
            field=models.CharField(default='default: not set', help_text='from the problem doc', max_length=255),
        ),
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='name',
            field=models.CharField(help_text='This is same as dataset_id for now', max_length=255, unique=True, verbose_name='Dataset Id'),
        ),
    ]
