# Generated by Django 2.1.5 on 2019-01-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0019_auto_20190128_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3mconfiguration',
            name='additional_inputs',
            field=models.TextField(blank=True, help_text='Additional inputs directory'),
        ),
    ]
