# Generated by Django 2.1.10 on 2019-07-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0020_d3mconfiguration_additional_inputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3mconfiguration',
            name='temp_storage_root',
        ),
    ]
