# Generated by Django 2.1.10 on 2019-07-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0021_remove_d3mconfiguration_temp_storage_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='problem_schema',
            field=models.TextField(blank=True, help_text='Input: Path to the problem schema'),
        ),
    ]
