# Generated by Django 2.1.10 on 2019-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0022_auto_20190717_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='problem_root',
            field=models.TextField(blank=True, help_text='Path to the directory containing the problem.'),
        ),
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='problem_schema',
            field=models.TextField(blank=True, help_text='Input: Path to the problem schema', verbose_name='D3MPROBLEMPATH'),
        ),
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='root_output_directory',
            field=models.TextField(blank=True, help_text='Not an official field.  Used for testing to determine the "/output" directory', verbose_name='D3MOUTPUTDIR'),
        ),
    ]
