# Generated by Django 2.1.10 on 2019-10-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0023_auto_20190718_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3mconfiguration',
            name='problem_root',
        ),
    ]
