# Generated by Django 2.2.10 on 2020-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0025_d3mconfiguration_is_selectable_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3mconfiguration',
            name='slug',
            field=models.SlugField(blank=True, help_text='auto-filled on save', max_length=255),
        ),
    ]
