# Generated by Django 2.1.5 on 2019-01-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0019_auto_20190128_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('orig_dataset_id', models.CharField(help_text='From D3MConfiguration orig_dataset_id', max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this workspace still usable?')),
                ('description', models.TextField(blank=True, verbose_name='optional description')),
                ('d3m_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.D3MConfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_active', 'modified', 'user'),
            },
        ),
    ]
