# Generated by Django 2.1.5 on 2019-01-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworkspace',
            options={'ordering': ('user', '-id', '-is_active')},
        ),
        migrations.AlterField(
            model_name='userworkspace',
            name='d3m_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.D3MConfiguration'),
        ),
    ]
