# Generated by Django 2.1.5 on 2019-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces', '0002_auto_20190128_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworkspace',
            options={'ordering': ('user', '-is_current_workspace', '-id', '-is_active')},
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='is_current_workspace',
            field=models.BooleanField(default=False, help_text='Workspace that the user is using'),
        ),
    ]
