# Generated by Django 2.1.7 on 2019-05-30 15:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces', '0003_auto_20190130_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkspace',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-filled if a ravens-config exists', max_length=255),
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='raven_config',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON data for the frontend'),
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='slug',
            field=models.SlugField(blank=True, help_text='auto-filled on save'),
        ),
    ]
