# Generated by Django 2.1.9 on 2019-06-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces', '0004_auto_20190530_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkspace',
            name='orig_dataset_id',
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='hash_id',
            field=models.CharField(blank=True, help_text='(auto-generated)', max_length=255),
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Share this workspace with others'),
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='original_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orig_workspace+', to='user_workspaces.UserWorkspace'),
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='previous_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_workspace+', to='user_workspaces.UserWorkspace'),
        ),
    ]
