# Generated by Django 2.1.10 on 2019-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workspaces', '0006_auto_20190619_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkspace',
            name='behavioral_log',
            field=models.FileField(blank=True, help_text='Behavioral log', upload_to='behavioral_logs/%Y/%m/%d/'),
        ),
    ]
