FROM python:3.6.8
MAINTAINER TwoRavens http://2ra.vn/

LABEL organization="Two Ravens" \
      2ra.vn.version="0.3-beta" \
      2ra.vn.release-date="2019-09-19" \
      description="Image for the base of the Two Ravens R service."

# ----------------------------------------------------
# This docker container runs "Flask-wrapped R",
# basically a flask server to run R scripts
# ----------------------------------------------------

# -------------------------------------
# Install debugging tools
# -------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils\
    iputils-ping \
    telnet \
    vim

# -------------------------------------
# Install Tex
# -------------------------------------
RUN apt-get -y install pandoc texlive-full && \
  tlmgr init-usertree

# -------------------------------------
# Install R and needed packages for
#   preprocess, discovered problems, etc
# -------------------------------------
RUN apt-get install -y r-base

#RUN R -e 'install.packages("rjson", repos="http://cran.rstudio.org")' && \
#    R -e 'install.packages("DescTools", repos="http://cran.rstudio.org")' && \
#    R -e 'install.packages("XML", repos="http://cran.rstudio.org")'


# -------------------------------------
# Install R packages for TwoRavens
# -------------------------------------
RUN R -e 'install.packages("Rcpp", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("VGAM", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("dplyr", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("Amelia", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("Rook", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("jsonlite", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("rjson", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("devtools", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("DescTools", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("nloptr", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("XML", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("rpart", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("tidyverse", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("lubridate", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("data.table", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("stargazer", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("doParallel", repos="http://cran.rstudio.org")'


EXPOSE 8000

#
# docker build -t tworavens/r-service-base-py:latest -f Dockerfile-pybase .
#
