apiVersion: v1
kind: Pod
metadata:
  name: raven1
spec:
  containers:
    - image: tworavens:v1
      name: raven1
      # liveness is for restart
      livenessProbe:
        httpGet:
          path: /monitoring/alive
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      # readiness: ready for traffic
      readinessProbe:
        httpGet:
          path: /monitoring/alive
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
