# This Kubernetes file creates a pod runing a TA2 and a TA3 container having a shared rw volume.
---
# Service for Nginx
apiVersion: v1
kind: Service
metadata:
  name: {{ eval_id }}
  labels:
    evalId: {{ eval_id }}
spec:
  # NodePort type allows to expose service outside the cluster
  type: NodePort
  selector:
    evalId: {{ eval_id }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
---
# TA3 and TA2 in the same pod
apiVersion: v1
kind: Pod
metadata:
  name: {{ eval_id }}
  labels:
    evalId: {{ eval_id }}
    main: "yes"
spec:
  restartPolicy: Never
  volumes:
  # Shared volume mount to both containers
  - emptyDir: {}
    name: shared-vol
  containers:
  # TA3 container, entry point for evaluation
  - name: ta3-main
    image: nginx:1.7.9
    ports:
      - name: http
        containerPort: 80
      - name: https
        containerPort: 443
    env:
    # environment variables passed to container
    - name: EVAL_ID
      value: {{ eval_id }}
    volumeMounts:
    - mountPath: /shared_dir
      name: shared-vol
      readOnly: false
  # TA2 container
  - name: ta2-main
    image: tensorflow/tensorflow:latest
    env:
    - name: EVAL_ID
      value: {{ eval_id }}
    volumeMounts:
    - mountPath: /shared_dir
      name: shared-vol
      readOnly: false
