compile:
  stage: build

  image: registry.gitlab.com/datadrivendiscovery/images/testing:ubuntu-artful-python36

  script:
    - |
      set -o errexit
      echo "Compiling"
      mkdir javascript golang python
      for fi in *.proto; do
          echo "File $fi"
          protoc -I . -I /protoc3/include ${fi} --go_out=plugins=grpc:golang/ --js_out=import_style=commonjs,binary:javascript/
          python3 -m grpc_tools.protoc -I . -I /protoc3/include --python_out=python/ --grpc_python_out=python/ ${fi}
      done
      echo "Linting"
      protoc -I . -I /protoc3/include --lint_out=. *.proto
      if [ ${CI_COMMIT_REF_NAME} = master -o ${CI_COMMIT_REF_NAME} = devel ]; then
        if [ -n "${GIT_ACCESS_USER}" -a -n "${GIT_ACCESS_TOKEN}" ]; then
          echo "Creating Python package"
          touch python/__init__.py
          echo "Pushing generated branches"
          if [ ${CI_COMMIT_REF_NAME} = master ]; then
            BRANCH_PREFIX=dist-
          else
            BRANCH_PREFIX=dev-dist-
          fi
          git clone https://${GIT_ACCESS_USER}:${GIT_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git --reference . generated &>/dev/null
          cd generated
          git config --local user.email noreply@datadrivendiscovery.org
          git config --local user.name "D3M CI"
          for lang in javascript golang python; do
            echo "Language $lang"
            git checkout -b ${BRANCH_PREFIX}${lang} --track origin/${BRANCH_PREFIX}${lang}
            rm -rf ./*
            cp -r ../${lang}/* ./
            echo ".pyc" > ./.gitignore
            echo "__pycache__" >> ./.gitignore
            git add .gitignore *
            if ! git diff --cached --quiet ; then
              git commit -m "Generated by CI." -m "Source commmit: ${CI_COMMIT_SHA}" -m "[skip ci]"
              git push https://${GIT_ACCESS_USER}:${GIT_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git HEAD:refs/heads/${BRANCH_PREFIX}${lang} &>/dev/null
            else
             echo "Nothing changed."
            fi
          done
        fi
      fi

  artifacts:
    paths:
      - javascript
      - golang
      - python

  except:
    - /^(dev-)?dist-.*$/
