# Generated by Django 2.0.5 on 2018-06-18 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ta2_interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, help_text='auto-generated', max_length=255)),
                ('workspace', models.CharField(max_length=255, verbose_name='Used to identify this problem')),
                ('request_type', models.CharField(max_length=255, verbose_name='API request name')),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ERROR', 'ERROR'), ('COMPLETE', 'COMPLETE')], max_length=255)),
                ('is_finished', models.BooleanField(default=False)),
                ('pipeline_id', models.CharField(blank=True, help_text='if applicable', max_length=255, verbose_name='Pipeline ID')),
                ('request', jsonfield.fields.JSONField(verbose_name='JSON sent by user')),
                ('hash', models.CharField(blank=True, help_text='auto-generated', max_length=255, verbose_name='Used for urls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='StoredResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_success', models.BooleanField(default=True)),
                ('sent_to_user', models.BooleanField(default=False, help_text='Sent to the UI for user viewing')),
                ('status', models.CharField(choices=[('ERROR', 'ERROR'), ('COMPLETE', 'COMPLETE')], max_length=255)),
                ('response', jsonfield.fields.JSONField(verbose_name='JSON received by the TA2')),
                ('hash', models.CharField(blank=True, help_text='auto-generated', max_length=255, verbose_name='Used for urls')),
                ('stored_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta2_interfaces.StoredRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StoredResponseTest',
        ),
    ]
