# Generated by Django 2.0.5 on 2018-06-18 20:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0002_auto_20180618_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedrequest',
            name='hash',
            field=models.CharField(blank=True, help_text='Used for urls (auto-generated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedrequest',
            name='request',
            field=jsonfield.fields.JSONField(help_text='JSON sent by user'),
        ),
        migrations.AlterField(
            model_name='storedrequest',
            name='request_type',
            field=models.CharField(help_text='API request name', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedrequest',
            name='workspace',
            field=models.CharField(help_text='Used to identify this problem', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedresponse',
            name='hash',
            field=models.CharField(blank=True, help_text='Used for urls (auto-generated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedresponse',
            name='response',
            field=jsonfield.fields.JSONField(help_text='JSON received by the TA2'),
        ),
    ]
