# Generated by Django 2.0.5 on 2018-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0003_auto_20180618_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedresponse',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='storedrequest',
            old_name='hash',
            new_name='hash_id',
        ),
        migrations.RenameField(
            model_name='storedresponse',
            old_name='hash',
            new_name='hash_id',
        ),
        migrations.AlterField(
            model_name='storedrequest',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('ERROR', 'ERROR'), ('COMPLETE', 'COMPLETE')], default='IN_PROGRESS', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedresponse',
            name='status',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('COMPLETE', 'COMPLETE')], default='COMPLETE', max_length=255),
        ),
    ]
