# Generated by Django 2.0.5 on 2018-06-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0004_auto_20180619_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedrequest',
            name='user_message',
            field=models.CharField(blank=True, help_text='Mainly for error messages', max_length=255),
        ),
    ]
