# Generated by Django 2.1.3 on 2018-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0007_storedresponse_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedresponse',
            name='pipeline_id',
            field=models.IntegerField(default=-1, help_text='Not always used'),
        ),
        migrations.AlterField(
            model_name='storedrequest',
            name='pipeline_id',
            field=models.IntegerField(default=-1, help_text='Not always used'),
        ),
    ]
