# Generated by Django 2.1.7 on 2019-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0008_auto_20181114_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedrequest',
            name='search_id',
            field=models.IntegerField(default=-1, help_text='Not always used'),
        ),
    ]
