# Generated by Django 2.1.7 on 2019-03-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0009_storedrequest_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedrequest',
            name='search_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
