# Generated by Django 2.1.7 on 2019-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0010_auto_20190313_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedresponse',
            name='sent_to_user',
            field=models.BooleanField(default=True, help_text='Sent to the UI for user viewing'),
        ),
    ]
