# Generated by Django 2.2.14 on 2020-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta2_interfaces', '0011_auto_20190314_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedrequest',
            name='user_message',
            field=models.TextField(blank=True, help_text='Mainly for error messages', max_length=255),
        ),
    ]
