# ---------------------------------------------------------
# TA3 Kubernetes Pod Stub File
# ---------------------------------------------------------
## Specifications
# * Assumes a web service over ports 80 (http) and 443 https
# * Assumes a listening port 5001 to listen to TA2 signals
# * In this speicification, the ta3-main container has the web ports
# but one can have a separate container handle the web ports
# that is not the TA3-main container
---
# Web Port Service (perhaps Nginx)
apiVersion: v1
kind: Service
metadata:
  name: {{ eval_id }}-ta3-web
  labels:
    evalId: {{ eval_id }}
    tier: ta3
spec:
  # NodePort type allows to expose service outside the cluster
  type: NodePort
  selector:
    evalId: {{ eval_id }}
    tier: ta3
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
---
# TA3 Service for taking requests from TA2
apiVersion: v1
kind: Service
metadata:
  name: {{ eval_id }}-ta3
  labels:
    evalId: {{ eval_id }}
    tier: ta3
spec:
  type: ClusterIP
  # There is a possibility of manually assigning an IP
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    evalId: {{ eval_id }}
    tier: ta3
---
# TA3 Pod
apiVersion: v1
kind: Pod
metadata:
  name: {{ eval_id }}-ta3
  labels:
    evalId: {{ eval_id }}
    main: "yes"
    tier: ta3
    ta3-main: "yes"
spec:
  restartPolicy: Never
  volumes:
  ##====|Begin| Required Code that NIST uses to pair TA2 and TA3 components |Begin|
    - name: nfs-data
      persistentVolumeClaim:
        claimName: pvc-datasets
    - name: nfs-output
      persistentVolumeClaim:
        claimName: pvc-rw
  ##====|End| Required Code that NIST uses to pair TA2 and TA3 components |End|
  # affinity:
  #   # Link pod affinity with
  #   podAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: evalId
  #           operator: In
  #           values:
  #           - {{ eval_id }}
  #       topologyKey: failure-domain.beta.kubernetes.io/zone
  containers:
  # TA3 container, entry point for evaluation
  - name: ta3-main
    image: <url_to_image>
    imagePullPolicy: Always
    command:
      - {{ command }}
    args:
      - {{ command_args }}
    # web (perhaps nginx) ports
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
      - containerPort: 443
        name: https
        protocol: TCP
      # Additional Port for TA3 to listen to TA2 signals
      - containerPort: 5001
        protocol: TCP
    env:
      # environment variables passed to container
      - name: EVAL_ID
        value: {{ eval_id }}
      # Query TA2 Service with service name:
      # {{ eval_id }}-ta2:45042
      # Query TA3 Service with service name:
      # {{ eval_id }}-ta3:5001
      - name: TA2_PORT
        value: "45042"
      - name: TA3_PORT
        value: "5001"
    volumeMounts:
      ##====|Begin| Required Code that NIST uses to pair TA2 and TA3 components |Begin|
      - name: nfs-data
        mountPath: /inputs
        subPath: {{ path_to_dataroot }}
        readOnly: true
      - name: nfs-output
        mountPath: /outputs
        subPath: {{ path_to_outputs }}
      ##====|End| Required Code that NIST uses to pair TA2 and TA3 components |End|
