apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.1.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rook-service
  name: rook-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rook-service
    spec:
      containers:
      - image: rook-service
        name: rook-service
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
