# Generated by Django 2.0.5 on 2018-05-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raven_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
